[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/producto/:id"
  query = {ssr = ":ssr"}
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/producto/:id"
  to = "/.netlify/functions/share-product?id=:id"
  status = 200

[[redirects]]
  from = "/api/share/product/:id"
  to = "/.netlify/functions/share-product?id=:id"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
